### ISSUE TITLE
please check the input

### ISSUE THREAD

**Issue by jindijamie** [Yangzhen0000/seasons-in-the-sun#1]
When I input "a b c", it keep running all the time!

**Comment by jindijamie** [comment]
Why using the word "losen"? I suppose it might be "lost".

**Comment by jindijamie** [comment]
What do you mean by "haven't gotten"? "haven't got"?

**Comment by Yangzhen0000** [comment]
Problems have been solved!

**Comment by Yangzhen0000** [comment]
My English is poor! Please do not be particular about my spelling and grammar, hahahaha.
